### ISSUE TITLE
Is there an eve.h file for the earlier eve devices - i.e. not eve3

### ISSUE THREAD

**Issue by cybersteve2018** [BRTSG-FOSS/pico-bteve#13]

**Comment by brtchip-tuannguyen** [comment]
@cybersteve2018 We don't have any file with name "eve.h",  can you explain what you expect in the "eve.h"?

**Comment by cybersteve2018** [comment]
I am referring to the file https://github.com/BRTSG-FOSS/pico-brteve/blob/main/c/basic/eve.h - this is the header file for Bridgetek display development on RP Pico. It has the memory allocations for the later eve2 and eve3 products,but not the original eve devices. I need to connect one of the original eve displays to RP pico.

**Comment by brtchip-tuannguyen** [comment]
@cybersteve2018 You can see definitions for any EVE in this header file: https://github.com/BRTSG-FOSS/EveApps/blob/master/common/eve_hal/EVE_GpuDefs.h

**Comment by cybersteve2018** [comment]
Thanks. That should help.
