### ISSUE TITLE
Improve the eve-flash programming application (bootloader for eve-flash programming)

### ISSUE THREAD

**Issue by brtchip-paul-jiao** [BRTSG-FOSS/pico-bteve#14]
Now we have this Pico application below based on tinyUSB to program Eve connected Flash(e-flash): 
https://github.com/BRTSG-FOSS/pico-brteve/tree/develop/tools/uf2

We want to add the support: 

- [x] Detect the SD card and read SD card to program the flash image to `e-flash`  if there is the pre-defined file "e-flash.bin" or "e-flash-v.bin" at the root directory. 
- [x] Read the eve-connected flash and write the data into SD card with the name `e-flash-readback.bin` if the pre-defined file "e-flash-v.bin" at the root directory. 
- [x] the pin assignment of Eve SPI interface by users (optional)

**Comment by brtchip-tuannguyen** [comment]
If e-flash.bin is detected and flashed, the INFO_UF2.TXT will have this line:

`X-Eve-Flash-image: /e-flash.bin`

Otherwise it has this line:

`X-Eve-Flash-image: NONE`

Example:
![image](https://user-images.githubusercontent.com/48436368/149736804-33304e9e-5eae-4a32-86e0-398804a07b36.png)

**Comment by brtchip-tuannguyen** [comment]
Commit 8331b72:

- [x] Read the eve-connected flash and write the data into SD card with the name e-flash-readback.bin if the pre-defined file "e-flash-v.bin" at the root directory.


![image](https://user-images.githubusercontent.com/48436368/150108670-5270119b-8a75-4954-a3c0-a7ab6e8cd872.png)

**Comment by brtchip-tuannguyen** [comment]
Added EFLASH.BIN entry so user can read the whole EVE's connected flash just by copying it on Window Explorer:

![image](https://user-images.githubusercontent.com/48436368/150109050-96afb0b5-d353-4230-9b98-9a39002f2978.png)

**Comment by brtchip-tuannguyen** [comment]
The pin assignment of Eve SPI interface by users is supported.

Usage: Edit file SPI_PIN.CNF directly by notepad and just save it to reflect the change.

![image](https://user-images.githubusercontent.com/48436368/151103228-a5e0acfd-6bee-4ec7-9e5c-f5b9b3e199c8.png)
