### ISSUE TITLE
Improve UF2 converter for Eve

### ISSUE THREAD

**Issue by brtchip-paul-jiao** [BRTSG-FOSS/pico-bteve#15]
- [x] The script `python uf2conv4eve.py -l` fails on Win11 because `wmic` is removed by Microsoft. So we need adapt the code to other way. 
![image](https://user-images.githubusercontent.com/13127756/148527011-d3dd8e52-2b9a-42fb-9b8c-c30a2bcd3591.png)

See here: 
https://winaero.com/microsoft-removed-the-wmic-tool-from-windows-11-dev-builds/
https://docs.microsoft.com/en-us/windows/win32/wmisdk/wmic

**Comment by brtchip-tuannguyen** [comment]
Now the script use PowerShell to get list drive.

If not found any drive, it try again with wmic\\wmix.exe and wmic command.
