### ISSUE TITLE
more document on pico BrtEve library

### ISSUE THREAD

**Issue by brtchip-paul-jiao** [BRTSG-FOSS/pico-bteve#18]
write more document on the APIs in the library
https://github.com/BRTSG-FOSS/pico-brteve/tree/main/circuitPython/lib/brteve

**Comment by brtchip-tuannguyen** [comment]
Added Doxygen generated document

![image](https://user-images.githubusercontent.com/48436368/149728144-ad1bc989-482a-4e05-b341-7a4d2a43c312.png)
