### ISSUE TITLE
bigger font eve_cocmd_text

### ISSUE THREAD

**Issue by qombajn** [BRTSG-FOSS/pico-bteve#23]
Is it possible to add bigger font in basic? Maximum is 31 and i need like 4 times bigger and 2-3 times bigger

**Comment by brtchip-paul-jiao** [comment]
BT81x has bigger font , such as 32,33,34.  You need call cmd_romfont to assign them to a valid font handle. See the example below: 

![image](https://user-images.githubusercontent.com/13127756/180714771-2a2ef6ff-887d-4eba-864c-3b063c734cd4.png)

**Comment by brtchip-paul-jiao** [comment]
![image](https://user-images.githubusercontent.com/13127756/180714935-d85959e6-3f21-45dd-8952-bafc20785380.png)

**Comment by brtchip-paul-jiao** [comment]
If you want bigger than Font 34,  you need use the custom font. Check the font converter of Eve Asset Builder for more details.

**Comment by qombajn** [comment]
Ok, but I am using basic in C examples in my project for raspberry pico and there is no cmd_romfont function and i don't know what i have to import to do it. I wanted to call that but it doesn't compile becouse i need some library or something.

**Comment by qombajn** [comment]
And I'm using 480x272.

**Comment by qombajn** [comment]
Could you explain me is it possible to use bigger font than 34, using raspberry pico? Becouse i understand that using windows you flash memory and then you have acces to this bigger fonts that you exported to eve. Is it possible with pico? Maybe 34 will be enough but i need little help how i discribed above

**Comment by brtchip-tuannguyen** [comment]
Hi [qombajn](https://github.com/qombajn), font size bigger than 34 can be done by using cmd_setfont2, please refer to [Font.c](https://github.com/BRTSG-FOSS/EveApps/blob/master/SampleApp/Font/Src/Font.c), function SAMAPP_Font_indexer().

Below is a screenshot:
![image](https://user-images.githubusercontent.com/48436368/180753062-a4357d9c-373d-44bd-8d21-86545fae1f2f.png)

You can try build and run C example code [Font](https://github.com/BRTSG-FOSS/EveApps/tree/master/SampleApp/Font) on RP2040, the instruction here: https://github.com/BRTSG-FOSS/EveApps/#raspberry-pi-pico

**Comment by qombajn** [comment]
I have build that but my project is based on basic example and there, in font example everything is different. I just need function romfont in basic example not remake project on font-example

**Comment by qombajn** [comment]
Can I change 16,17,18 to 32,33,34 in example-basic??

**Comment by qombajn** [comment]
Ok I did it:
You have to send:
eve_cocmd_ddd(CMD_ROMFONT,font,romfont) 
font and romfont are uint32_t
