### ISSUE TITLE
Support Telemetrix for Pico 

### ISSUE THREAD

**Issue by brtchip-paul-jiao** [BRTSG-FOSS/pico-bteve#8]
Full user guide on Telemetrix for Raspberry Pi Pico: 
https://mryslab.github.io/telemetrix-rpi-pico/

SPI has been updated in client-side (Raspberry Pi Pico) and the working code of server-side can be found here: 
https://github.com/MrYsLab/Telemetrix4RpiPico/issues/2

We may port the `lib\brtEve` to control pico by UART through Telemetrix library.  It enables writing the pure Python code on PC 
to control Eve

**Comment by brtchip-tuannguyen** [comment]
Ported telemetrix into brteve 

Also added a hello world example:

![image](https://user-images.githubusercontent.com/48436368/144375482-732b6231-27d5-415a-8034-e1bed6d0c413.png)

![image](https://user-images.githubusercontent.com/48436368/144375592-7ea831d7-16e1-40ea-a6c9-f0704b6db44b.png)

**Comment by brtchip-tuannguyen** [comment]
Trying to run another example such as "bubble-code.py" but not success

![image](https://user-images.githubusercontent.com/48436368/144375967-deaa6289-917e-47a2-9b32-5e6349c1f4fe.png)

**Comment by brtchip-tuannguyen** [comment]
Ported some example from circuitpython to Telemetrix: 
- qix-code.py
- helloworld-code.py
- flashinfo.py
- fizz-code.py
- circle-progress-bar.py
- bubble-code.py

**Comment by brtchip-tuannguyen** [comment]
On Telemetrix, we use EVE's command buffer 24 bytes only, because the server side use a buffer 30 bytes (MAX_COMMAND_LENGTH).

The Telemetrix's command header included 4 bytes, so totally command buffer is 28 bytes.

**Comment by brtchip-tuannguyen** [comment]
On CircuitPython _EVE build-in class, EVE's command buffer is 512 bytes

**Comment by brtchip-paul-jiao** [comment]
I logged a ticket https://github.com/MrYsLab/Telemetrix4RpiPico/issues/11 to increase the limit of command length of Telemetrix.
